# Generated by Django 3.1.3 on 2020-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(default='saknd', upload_to='course_pictures'),
        ),
    ]
